name: virtual_keyboard_plus
description: A customizable on-screen keyboard widget for Flutter with multiple layouts and RegExp-based input validation.
version: 2.0.2
homepage: https://github.com/Prameshbasnet/virtual_keyboard
repository: https://github.com/Prameshbasnet/virtual_keyboard
issue_tracker: https://github.com/Prameshbasnet/virtual_keyboard/issues
license: MIT

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/AlphanumericKeyboard.png
    - assets/DualKeyboard.png
    - assets/NumericKeyboard.png
